services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    volumes:
      - ./backend:/app
    environment:
      - DEBUG=0
      - SECRET_KEY=${SECRET_KEY:-default-secret-key-change-me}
      - ALLOWED_HOSTS=neretva.mknz.si
    command: >
      sh -c "python manage.py migrate &&
             python manage.py create_initial_data &&
             python manage.py collectstatic --noinput &&
             gunicorn scrum_project.wsgi:application --bind 0.0.0.0:8000"
    restart: always
    networks:
      - scrumflow_network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend.prod
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=https://neretva.mknz.si/api
    restart: always
    networks:
      - scrumflow_network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt/live/neretva.mknz.si/fullchain.pem:/etc/letsencrypt/live/neretva.mknz.si/fullchain.pem:ro
      - /etc/letsencrypt/live/neretva.mknz.si/privkey.pem:/etc/letsencrypt/live/neretva.mknz.si/privkey.pem:ro
    depends_on:
      - backend
      - frontend
    restart: always
    networks:
      - scrumflow_network

networks:
  scrumflow_network:
    driver: bridge

volumes:
  frontend-node-modules: 