# Generated by Django 4.2.7 on 2025-04-27 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0012_alter_userstory_status'),
        ('tasks', '0005_task_is_deleted'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='task',
            unique_together={('title', 'story')},
        ),
    ]
