# Generated by Django 4.2.7 on 2025-04-27 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_alter_task_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='remaining_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
