# Generated by Django 4.2.7 on 2025-04-12 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprints', '0002_alter_sprint_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
