# Generated by Django 4.2.7 on 2025-03-15 20:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('sprints', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('acceptance_criteria', models.TextField()),
                ('priority', models.CharField(choices=[('MUST_HAVE', 'Must Have'), ('SHOULD_HAVE', 'Should Have'), ('COULD_HAVE', 'Could Have'), ('WONT_HAVE', "Won't Have This Time")], default='SHOULD_HAVE', max_length=100)),
                ('business_value', models.PositiveIntegerField(default=0)),
                ('story_points', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('DONE', 'Done'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='NOT_STARTED', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_stories', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to='projects.project')),
                ('sprint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stories', to='sprints.sprint')),
            ],
            options={
                'verbose_name_plural': 'User stories',
                'ordering': ['-priority', '-business_value'],
                'unique_together': {('project', 'title')},
            },
        ),
        migrations.CreateModel(
            name='UserStoryComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='stories.userstory')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
