# Generated by Django 5.1.7 on 2025-03-22 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('sprints', '0002_alter_sprint_project'),
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userstory',
            old_name='acceptance_criteria',
            new_name='acceptance_tests',
        ),
        migrations.RenameField(
            model_name='userstory',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='userstory',
            old_name='description',
            new_name='text',
        ),
        migrations.AlterUniqueTogether(
            name='userstory',
            unique_together={('project', 'name')},
        ),
        migrations.AlterField(
            model_name='userstory',
            name='business_value',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='userstory',
            name='priority',
            field=models.CharField(choices=[('must have', 'Must Have'), ('should have', 'Should Have'), ('could have', 'Could Have'), ("won't have this time", "Won't Have This Time")], max_length=50),
        ),
        migrations.AlterField(
            model_name='userstory',
            name='sprint',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_stories', to='sprints.sprint'),
            preserve_default=False,
        ),
    ]
