# Generated by Django 4.2.7 on 2025-03-24 12:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stories', '0002_rename_acceptance_criteria_userstory_acceptance_tests_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstory',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_stories', to=settings.AUTH_USER_MODEL),
        ),
    ]
