# Generated by Django 4.2.7 on 2025-03-31 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sprints', '0002_alter_sprint_project'),
        ('stories', '0003_alter_userstory_created_by'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userstory',
            unique_together={('name',)},
        ),
        migrations.AlterField(
            model_name='userstory',
            name='priority',
            field=models.CharField(choices=[('MUST_HAVE', 'Must Have'), ('SHOULD_HAVE', 'Should Have'), ('COULD_HAVE', 'Could Have'), ('WONT_HAVE', 'Wont Have')], default='MUST_HAVE', max_length=50),
        ),
        migrations.AlterField(
            model_name='userstory',
            name='sprint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_stories', to='sprints.sprint'),
        ),
        migrations.RemoveField(
            model_name='userstory',
            name='project',
        ),
    ]
