# Generated by Django 4.2.7 on 2025-04-07 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_product_owner_and_more'),
        ('sprints', '0002_alter_sprint_project'),
        ('stories', '0004_alter_userstory_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userstory',
            unique_together={('sprint', 'name')},
        ),
        migrations.AddField(
            model_name='userstory',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stories', to='projects.project'),
        ),
    ]
