# Generated by Django 4.2.7 on 2025-04-12 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0008_userstory_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstory',
            name='status',
            field=models.CharField(choices=[('BACKLOG', 'Backlog'), ('SPRINT', 'In Sprint'), ('IN_PROGRESS', 'In Progress'), ('REVIEW', 'In Review'), ('DONE', 'Done'), ('REALIZED', 'Realized')], default='BACKLOG', max_length=15),
        ),
    ]
