# Generated by Django 4.2.7 on 2025-04-13 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0009_alter_userstory_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstory',
            name='status',
            field=models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('DONE', 'Done'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='NOT_STARTED', max_length=15),
        ),
    ]
