# Generated by Django 4.2.7 on 2025-04-13 09:53

from django.db import migrations

def fix_invalid_story_statuses(apps, schema_editor):
    """
    Update all stories with invalid status values to use valid ones
    - "BACKLOG" → "NOT_STARTED"
    - "REALIZED" → "ACCEPTED"
    - "SPRINT" → "IN_PROGRESS"
    """
    UserStory = apps.get_model('stories', 'UserStory')
    
    # Update all stories with invalid status values
    UserStory.objects.filter(status='BACKLOG').update(status='NOT_STARTED')
    UserStory.objects.filter(status='REALIZED').update(status='ACCEPTED')
    UserStory.objects.filter(status='SPRINT').update(status='IN_PROGRESS')


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0010_alter_userstory_status'),
    ]

    operations = [
        migrations.RunPython(fix_invalid_story_statuses, migrations.RunPython.noop),
    ]
