# Generated by Django 4.2.7 on 2025-04-20 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0011_fix_invalid_story_statuses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstory',
            name='status',
            field=models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('DONE', 'Done'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('BACKLOG', 'Backlog (Legacy)'), ('SPRINT', 'In Sprint (Legacy)'), ('REVIEW', 'In Review (Legacy)'), ('REALIZED', 'Realized (Legacy)')], default='NOT_STARTED', max_length=15),
        ),
    ]
