# Generated by Django 5.2 on 2025-04-27 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprints', '0003_sprint_is_completed'),
        ('stories', '0012_alter_userstory_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstory',
            name='finished_in_sprint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finished_stories', to='sprints.sprint'),
        ),
    ]
